# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ubiquitous Genomics
tagline:          'A Jekyll theme'
description:      'COMSE6998'
url:              https://ubiquitousgenomics.github.io
baseurl:          /

author:
  name:           'Yaniv Erlich'
  url:            https://twitter.com/erlichya

paginate:         5

# Custom vars
version:          2015

github:
  repo:           https://github.com/ubiquitousgenomics/ubiquitousgenomics.github.io


affilation:       
  img1:           '/public/img/columbia_logo.png'
  img2:           '/public/img/nygenome_logo.png'
